name: Push changes to RepoD

on:
  push:
    branches:
      - main  # Este flujo se activa cuando hay un push en la rama 'main' de RepoC

jobs:
  push_to_dev:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código de la rama 'main' de RepoC
    - name: Checkout RepoC main branch
      uses: actions/checkout@v2
      with:
        ref: main

    # Paso 2: Configurar Git para los commits automáticos
    - name: Set up Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    # Paso 3: Crear un directorio temporal único para clonar el repositorio RepoD
    - name: Create unique target directory and clone RepoD
      env:
        TOKEN_BACK: ${{ secrets.secret1 }}  # Secreto configurado con el valor de 'token1'
      run: |
        dir=$(mktemp -d)
        git clone --branch main https://x-access-token:${{ secrets.secret1 }}@github.com/gonzalo1998peru/RepoD.git $dir
        rsync -av --exclude='.git' ./ $dir/
        cd $dir
        git add .
        git commit -m "Auto-sync from RepoC/main"
        git push origin main